global function InitEncounterType_SpectreHitSquad


const string MY_TYPE = "spectrehitsquad"
void function InitEncounterType_SpectreHitSquad()
{
	#if SERVER
		                             
		                            

		                                            
	#endif          
}

#if SERVER
                                                      
 
	                      
	 
		                     
			           
	 
	            
 

                                                                 
 
	                                         
	                   
	                            
	 
		                         
			        
		             
	 

	           
 


                                                                        
 
	                               
	 
		                                             
		      
	 

	        
	 
		                                                           
		                               
		 
			                                                            
			      
		 

		                                                                                                          
		                                          
	 

	         
	                  
	 
		                                
		                                                                      
		                                                             

		                                   
		 
			                                                                                      
			                      
				        
			                  
		 

		                                      
	 

	           
	                      
	 
		                     
			                                         
	 

	          
	 
		           
		                                  
			     
	 
 
                                                                       
 
	                               
 

#endif          
