global function ControlGunRacks_Init
global function ControlGunRacks_GetCoolDownDuration
global function ControlGunRacks_GetPickupGracePeriodDuration

global const string CONTROL_GUN_RACK_CLASS_NAME = "control_gun_rack"

#if SERVER
                                                          
                                                                    
                                                         

       
                                                  
      

                                                                    
                                                                                
                                                  
                                                   
#endif          
const float DELAY_BEFORE_RESET_GUNRACK = 1.0
const float CONTROL_GUNRACK_PICKUP_GRACE_PERIOD = 5.0

struct
{
#if SERVER
	                         
	                              
	                                                              
	                                    
	                            
	                                
	                
	                                         
	                                    
	                                       
	                                                          
	                                          
#endif
	float delayBeforeResetGunRack
	float controlGunRackPickupGracePeriod
} file


void function ControlGunRacks_Init()
{
		if ( !GetCurrentPlaylistVarBool( "control_enable_gunracks", false ) )
		{
			#if SERVER
				                                                                                
			#endif          
			return
		}

		#if SERVER
		                              
		                                  
		                                                                                                            
		                                                
		                                                                           
		                                                                                                    
		                                                                                                                        
		                                                                                                                                                   
		#endif          
		file.delayBeforeResetGunRack = GetCurrentPlaylistVarFloat( "control_gunracks_delay_before_reset", DELAY_BEFORE_RESET_GUNRACK )
		file.controlGunRackPickupGracePeriod = GetCurrentPlaylistVarFloat( "control_gunracks_pickup_grace_period", CONTROL_GUNRACK_PICKUP_GRACE_PERIOD )
}

#if SERVER
                                                          
                                                                
 
	                                     
	                                  

	                                                             
	                                                                 
 

                                 
 
	                                                                                                     
	                                                             
	                                  
	 
		                                                             
		                                                                      
			                                                
	 
 

                              
                                                                                                             
 
	                        
	                                      
	 
		                                                     
			                       
	 

	                                                             
	                                                                         
	                                                                       

	                                                                                                                                                 
	                                             
	 
		                                                                                          

		                                          
			                                                                                        
	 
	
	                                                                                             
	                                                                                                                                          
	 
		                                        
		      
	 
	    
	 
		                                                                    
		                                          
		                                        
		                                           

		                                                                                                                                                               
		                                                                           
		 
			                            
			                                                                                           
		 
		                                 
	 
 

                                                                                                          
                                                             
 
	                                      
	 
		                                                
		                                      
			                                      

		                                      
		                         
			                 
	 

	                                         
	 
		                                         
	 

	                                     
 

                                              
                                                       
 
	                       
 

                                                                                                                  
                                                                                                                                                                      
 
	                                      
	 
		                                                
		                                        

		                                                                                                 
		                                                                        
		 
			                                                                                                         
		 
		                                                                            
		 
			                                                                                                                                      
			                                                             

			                                                                                                                                                                                 

			                                                                          
		 
	 
 

                                                                                                               
                                                                                                                                               
 
	                          

	            
		                                                                     
		 
			                                                                                   
			 
				                                                                       
			 
		 
	 

	                        

	                                                                                          
	                            
	 
		                     
		                                            
		 
			                                                                                                         
			 
				                      
				     
			 
		 

		                     
		 
			     
		 

		                                        
	 
 

                                                                                                                 
                                                                                                                                         
 
	                              
	                                                                                                

	                                    
	 
		                                                                                                                                         
		 
			                                  
		 
	 

	                                                                                                                
	                                                                            
 

                                                                                                                                                    
                                                                                                                   
 
	                                                                                                                                                                                    
	                                                                                         
	                                               
	                                                                            
 

                                                  
                                                                                                        
 
	                   

	                                                                                                                    
	                               

	                                                                    
	 
		                                                                                      
		                                                                                                  
	 

	                                                                                         

	                                  
	 
		                              
			                                                                                      

		                                                                                                  
		                                                                           
	 

	                                      
	              
 

                                                                                                   
                                                                                                  
 
	                           
	                                                                                                                                                                                                                 
	                                                                                   
	                                      
	 
		                                                               
		 
			                                                     
		 
	 

	               
 

                                                                                                      
                                                                                              
                                                                                          
 
	                                       
	 
		                                      
	 
	    
	 
		                                                                                                            
		                                                                                                             
	 

	                                                          
	 
		                                                                               
			                                                                     
	 
	    
	 
		                                
		                              
		                                                                   
	 

	                                                         
	 
		                                               
		                                                                                    
		                                                                           
	 
 

                                                    
                                                               
 
	                               
 

                                                                       
                                                                  
 
	                                                                                      
 

                                                                        
                                                                                                                                                    
 
	                                                                                           
	                                                                                              
 

                                                                                                                                
                                                                                                                                        
 
	                                                         
	                           
	                

	                               
	 
		              
		                                                      
			                                                   

		                                                                                            
		                     
	 
 

                                                                                                                           
                                                                                                                        
 
	                          

	            
		                                                                     
		 
			                                           
			 
				                                        
				                                                                                                                    
			 
		 
	 

	                                                                                          
	                            
	 
		                     
		                                            
		 
			                                                                                                         
			 
				                      
				     
			 
		 

		                     
		 
			     
		 

		                                        
	 
 

                                                                                                                            
                                                              
 
	                    
	                                       
	 
		                                                              
	 
	    
	 
		                                                                                                                                                        
		                                                                                                                                                         
	 

	                   
 

                                                   
                                                                                      
 
	                                   
		      

	                                                       
	 
		                                                               
		 
			                                                       
			                                                               
				                                                               
		 
	 
	    
	 
		                                                        
	 
 

                                              
                                                                           
 
	                                                       
 

       
                                                  
 
	                                             
	 
		                                               
	 
 

      
#endif          

float function ControlGunRacks_GetCoolDownDuration()
{
	return file.controlGunRackPickupGracePeriod + file.delayBeforeResetGunRack
}

float function ControlGunRacks_GetPickupGracePeriodDuration()
{
	return file.controlGunRackPickupGracePeriod
}
