global function InitObjectiveType_DropDownFight

#if SERVER
                                              

                                       
#endif          

void function InitObjectiveType_DropDownFight()
{
#if SERVER
	                             
	                        
	                                               
	                                                            
	                             

	                                            
#endif          
}

#if SERVER

                   
 
	                           
 

  
                                                                                                    
 
	                                                                                                                                    
	 
		                                            
			          
	 
	           
 
                                                                       
 
	                                                                  
 
                                                                           
 
	                                                                      
 

                        
 
	                           
	                              
	                                  
 

                                                                  
 
	                                  
	                             
	 
		                                                          
		                                                                                   
		                               
	 

	                              
	                                                        
	 
		                      
		                     

		                                                 
		                                                         

		                                          
		                    
		                              
		 
			                                                                          
			 
				              
				     
			 
			                                                                                      
			 
				              
				     
			 
		 
		              
			        
		                    
	 

	                           
	                        
	 
		                                                                
		                                                           
		                                                                   

		                                                               
			        

		                   
		                                   
		                        
	 

	              
 


                                                  

           
             
 
	             
 
                                      

                                               
 
	              
	                               
	                         
	                                 
	 
		                                            
		                     
	   
 
                                               
 
	                     
 
           

                                           
 
	                                                                

	                                   

	  

	                       

	                                                               

	                                                                     

	                                                                          
	                                                         

	                    
	                                
	                                

	                             
	                      
	                         

	                        
	                                                             
	                                                                     
	                                                
	                                                               

	                
	             
	 
		                                   
		          
		                                                       

		                                                          
		                        
		 
			       
				                                                                                                         
				     
			       
				                                                                                                         
				     
			       
				                                                                                                         
				     
			       
				                                                                                                         
				     
		 

		                          
			     
	 

	           
	                                                            
	           
	                                        

	           
	                           
	 
		                                 
			                               
		                            
		                                                                                                              
	 

	                  
	 
		                                  
			                     
			                     
			                     
			                     
			                             
			                             
		 
		                          
		                                                                           
	 

	             
 

                                                                                    
 
	                                                                                              
 

                                                                                                   
 
	                                
		                                

	                      
 

                                                                                            
 
	                                                                                                            

	                                                 
	               
	                                             
	                                                          
	                                                           
	                                                        

	                                                                                                       
	                   
	                                             
	                                              

	                                 
	                               

	                                                                                                                               
	 
		                         
			      
		                         
			      

		                                                                           
		                                                                                                            

		             
		            
		                               

		                                  
			                            
		 
		                                
		                          
			                                                              

		                          	                                                             
		                                                                                                       
	   

	          
 

                                                                                         
 
	        
	 
		                                
		                                                                             
		                    
		 
			                             
			                                 
			 
				                           
				                                                                                                                

				  
				                                                                        
				                  
				                                                   
				 
					                                  
						     

					                                                                                
					                                                                                          
					                                 
					                                   
				 
				  
			 
		 
	 

	            
	 
		                                     
		                                                                                 
		                    
		 
			                             
			                                 
			 
				                           

				                                                                        
				                  
				                                                   
				 
					                                      
						     

					                                                                                               
					                                 
					                                   
					                                     
					                                   
					                                    
				 
			 
		 
	 
 

                                                                             
 
	                                 
	                                                            
	                    
		            
	                                                        
	                    
		            

	           
 

                                                                                           
 
                    
                                                   
                                                                 
                      
         
                               

                                                                        
                       
                                              
   
                                  
                             
                                                                                                 
                                  
                                                                 
                                                                                    
   
       
 

                                                                      
 
                    
                                                                                          
                                                                           
                       
                      
                                             
   
                                  
                                                               
    
                                  
                  
    
                                                                                    
   
       
 


                                                      
 
	                         
	 
		                            
		                          

		                                      
		                                       
		                                               
		                                                 

		                                      
		                                       
		 
			                                               
			                                                                        
			                                             
			                                               
		 
	   
 

                                                                                                                                                                   
 
	                                                                                                                            
	                                                                         
	                        
	 
		                                                                
		      
	 

	                
	                                                                     
	 
		                                                         
		                                                         
		                            
			         
		                            
			        
		        
	   

	                                                  
	 
		                                 
			     
		                                       
		                         
			        

		                                                                      
		 
			                                 
			                    
			                                                                                       
			                        
			 
				                         
					                                                 
			 
		   
	 
 

                                                                               
 
	                            
	                            
		                                                  
	              
 

                                                             
 
	                                                                                        
	                                                                                           
	                                                                         
	                          
		                                                                                          
 

                                                                   
 
	                                                                              

	                                                                                        
	                                                                                  
	                  
	                                                   
	 
		                           
			     

		                                                                                               
		                                   
		                                   
	 
 

                                               
                                                                                                     
 
	                      

	                                                        
	                     

	                          
	                                                        
	                                                                                                           
	                                                     
	                                                                     
	                                     
	                                                    

	                                                           
	         
 

                                                                            
 
	  
	                                                           
	 
		                                                       
		                      
		                                                     
		 
			                                                           
				                
		 
		                
			        

		                                                                    
			        

		                              
		                                  
		                                           
		                                             
		                                                             
		                                                                                     
		                                           
		                            
	 
	  
 

  
  
  

                                                                   
 
	                                      
	                       
	 
		                          
			        
		                                                    
			        

		                                                              
		                                                                    
		 
			                                    
		   
	 
	  
 

#endif          
