global function InitObjectiveType_NightrunExample

#if SERVER
                                                

                                         
                                                        
                                                     
#endif          

void function InitObjectiveType_NightrunExample()
{
#if SERVER
	                             
	                              
	                                               
	                                                            
	                             
	                                              
	                                              

	                                            
#endif          
}

#if SERVER
             
 
	                       
	              
 
                                                
                                                    

                                           
 
	                                                                

	           
	                                
	                               

	  
	                                                    
	                                                              

	  
	                                           
	                                         

	                       

	                           

	                                          

	                                          
	             
	 
		           

		                                   
		                                                                                                  
			                                          

		                    
		                                            
			     
	 

	           
	                                                   
	           
	                                        
 

                                                                                    
 
	                                                                                              
 

                                                                               
 
	                                      
	                                   
		                                                                                                                   

	                                
	                                         
	                                                                                    
		           
		                                         
		 
			                                         
		  
		          
		                                         
		 
			                                        
		 
	 
 

                                                                                       
 
	           

	                                                                     
	                                             
	                                            

	         
	 
		           

		                  
		                                           
		 
			                                                            
				            
		 
		            
			     
	 

	                                   

	         
	 
		           

		                  
		                                           
		 
			                                                           
				            
		 
		            
			     
	 

	                                 
	            
	                                           

	                                        
 

                                                  
 
	                               
 

                                                       
 
	                                     

	                              
 

                                                                               
 
	                      

	                                                   
	                     

	                          
	                       
	                                                        
	                                                     
	                            	                                                     
	                                     

	                                                           
	         
 

                                                                            
 
	  
	                                                           
	 
		                                                       
		                      
		                                                     
		 
			                                                           
				                
		 
		                
			        

		                                                                    
			        

		                              
		                                  
		                                           
		                                             
		                                                             
		                                                                                     
		                                           
		                            
	 
	  
 


#endif          
