global function InitObjectiveType_ShackAttack


const string MY_TYPE = "shackattack"
void function InitObjectiveType_ShackAttack()
{
#if SERVER
	                             
	                              
	                                               
	                                                            
	                            
	                                              

	                                            
#endif          
}

#if SERVER
                                                   
                                    
                                     
                                                                            
 
	                                                          
	                      

	                                            
	                                                                                                                          
	                                             
	 
		                                                            
		                 
			        
		                                                     
			        
		                                                                                        
			        
		                 
		                                                                       
			        
		                                                                         
			        

		                              
			                             
		    
			                                  
	 

	                                           
	 
		                                                

		                       
		                           
		                        
		                                                         
		                                                         
		                                              
		                                         
		                     
	 
 


             
 
	                         
	                        

	             
 
                                      

                                          
 
	                                                                
	                                      

	                       
	                                                  
	                                              

	  
	           
	                      

	                  
	                                                                       
	                                                        
	                                           
	                             
	                                                                                    
		           
		                                         
		 
			                                           
		  
		          
		                                         
		 
			                                          
		 
	 

	                 
	                                                                     
	                                                      
                           
                                                   
     
	                                          
      
	                            
	                                                                                    
		           
		                                         
		 
			                                          
		  
		          
		                                         
		 
			                                         
		 
	 

	                                                                   

	                                                    
	                                                                   
	                                                     

	                 
	                                 
	         
	 
		           

		                                                                                                 
			                                                   
		                             

		                                                                           
		                           
			                                              
		                                                                                                                
			                                                                        
		                   
		                                 
			     
	 

	           
	                                                   
	                                                      
	           
	                                        
 
                                                  
 
	                     
 

                                                                             
 
	                                                                                                
 

                                                                              
 
	                                                                                                
 
#endif          
