                                  

#if SERVER
	                                      
	                                     
	                                           
	                                                             
	                                                   
	                                                    
	                                                         
	                                                              
	                                         
	                                      
	                                         
	       
	                                
	      
#endif         

#if CLIENT
	                      
#endif         

global const string EVAC_DROPSHIP_TARGETNAME = "evac_dropship"

#if SERVER
	                                                                         
#endif         

const int	EVAC_SHIP_PASSENGERS_MAX = 6
const float DEFAULT_TIME_UNTIL_SHIP_ARRIVES = 60
const float DEFAULT_TIME_UNTIL_SHIP_DEPARTS = 30
const float DEFAULT_EVAC_RADIUS = 256
const float EVAC_SHIP_Z_OFFSET = 128

#if SERVER
                          
 
	               
	                      
	                  
	                         
	                         
	                        
	                  
	                  
	                          
	                                                    
	                                                     
	                                                              
	                                                                  
	                                                               
	             
	             
	                
	                                                                                                                                                                                                                                 
	                                                                                                                                 
	                          
	                      
	                    
	                              
	                                    
	                              
	                               
 
#endif         


struct
{
	#if SERVER
		                           	                   
	#endif         
} file


#if SERVER
                                                                                                                                                                                                                                                                                                                                                   
 
	       
		                                                 
			           
	      


	                                                                  
	                           
	                           
	                           
	                                                                                                                                     
	                                                                                                                    
	                           
	                        
	                   
	                          
	                             
	                                   
	                           
	                            
	                            
	                                                       
	                                                   

	                           
	               
	                           
	                         
	                                                
	                                    
	                                    
	                         
	                        
	                                 
	                                   
	                                       

	                     


	                   
	                         
	                    
	                                                                                                                                                                                                
	                                                                                  
	                         
	                          

	                   
	 
		                                                                   
		                                 
			                                                                                                                                                                                           

		                                                                                                                                                             
		                           
		                           
		                                
		 
			                           
			 
				                           
				                                                      
			 
		 
	 


	                   
	                     
	                    
	                                                                                    
	                                
	 
		                                                                                     
		                                                                            
	 

	                   
	              
	                    
	                         
	                                
	                                   
	                                   
	                                      
	                                        
	                                        
	                                   
	                                        
	                            
	                            
	                                        
	                                                                
	                                                    

	                                                    
	                                       

	                            
 
#endif



#if SERVER
                                                           
 
	                   

	                                       
	                                                     
	                                                                                                                                       
	                                       

	                                              
	                                                      
	                                           
	                                                    


	             
	          
	             
	                                          
	 
		                          

		                                              
			                                      

	  

	             
	          
	             
	                                                             
	                                                                  
	                                     

	                 
	                 
	                 
	                    
	                                               

	                       
	                     
	                       
	                                     
	                                                                     
		                        

	                                                       
	                          
	                                              
		                                                                                                                                                                                                           



	                                             
	 
		                                                                                                       
		                                       
		 
			                    
				            
		 
		                           

		                                                                                                              
		                                                                                                              

		                                    
		                                    
		                                         
		                                         

		                                               
		                                               

		                                    

		                                                                                                                                                                                            
	 

	                                                                                                                                                                          
	                           
	                                        

	               
	                      
	                
	                                                             
	                                                                
	                                                               
	                                                               
	                            
	                                                                           


	                       
	                                
	                       
	                                                
	                           
	                                            
	                                             
	                                                           
		                        

	                                                             

	                                  
	                        
	                                                               
	                                                               

	                                                                              

	                        
	                       
	                        
	                          

	                                       
	 
		                    
			            
	 

	                                                                                                                      
	                             
	                                                                        
	                                                 
	                                                            
		                        

	                                                              
	                                   
	                           
	                                           
	                                            
	                                         
	                                 
	                                                               
	                                                                  

	                                                             
		                

	                                                                                   
	                                                                                                                          
	                                                                                                                          
 
#endif         


#if SERVER
                                                                         
 
	          

	                         
		                 
 
#endif         


#if SERVER
                                                                                          
 
	                                         
 
#endif         

#if SERVER
                                                                     
 
		              
		                      
		 
			                                 
			                                                  
				                                           
			      
		 


		                      
		 
			                                    
			                                                  
				                                           
			      
		 

		                                      
		                           
		 
			      
		 

		                                                          

		                        
		 
			                                          
			                                                  
				                                           
			      
		 


		                          
		 
			                                                
			                                                  
				                                           
			      
		 


		                                               
			      

		                                            

 
#endif

#if SERVER
                                                   
 
	                   
	                                                                                                                 
	                                

	                                                 
	                                                   
	                                                   
	                                                   

	                                      
	                           
	 
		      
	 

	                                                          

	              
	 
		         
		                                                                                                                                                           
		                                           
		 
			                         
				        
			                                                                 
				        

			                                                 
			                                   
			 
				                                            
				        
			 

			                                                                                           
			                                                                         
			 
				                                            
				        
			 
		 
	 
 
#endif         

#if SERVER
                                                                              
 
	                         
		      

	                             

	                     
	                           
		                     

	                              
	                                                                             
	 
		                                              
		  
		                                                                       
		                        
		 
			                                                                                         
			 
				                                   
				                                     
				                               
				                                              
				                                           
			 
		 
		  
	 

	                            
	                                  
	                             
		                     
	                                           

	                               
		                        

	                                                                     
	                                                                
		                                     

	                                                                 
	                                              
	                                              
	                                                        
	                                             

	                                                                
	                                
		                 

	                          
	                              
	                                   
	                                       
	                                        
	                                                                      

	                                           
	                                           
	                                           
	                                                      
	                                       
	                                                                 
		                                

	                                             
	                                         
	                                             
	                                     
	        

	                          
	                        
	                          
	                                                         
	                                                                                                                             
	                                                   
	                                     

	                                                         
	                                                              
	                                                              

	                               
	                                 

	                                  
	 
		                          
		                  
		           
		           
	 

	                                  
	                                
	                                
	                                                       
	                                  
	                                                     
	                                                      
	 
		                       
		                                              
	 

	                                                 

	                                                                                     
	                      
	                                    
		                                                    
		 
			                         
				      

			                                                                  
			                                                                         
			                                                                                                                                                                                                                                      

			                                     
		 
	 

	                                                         
	                                   
		                                                   
		 
			                                                                  
			                                                                         
			                                                                                                                                                                                                                               
		 
	 

	                                         

	                             
	                                                                                                   
	 
		                                                    
		      
	 

	                                  
	                                                       
		                                                                                   
 

                                                                         
 
	                                                                            
	                                     
	 
		                                           
			           
	 
	            
 
#endif         

#if SERVER
                                                                    
 
	                                                    
	                                                                     
	                       
	 
		                       
		                       
		                           
		                           
		                           
		                           
			           
	 

	            
 
#endif         



  
                                                                                                                       
                                                                                                                       
                                                                                                                       

                                                          
                                                         
                                                        
                                                       
                                                       
                                                       
                                                       

                                                                                                                       
                                                                                                                       
                                                                                                                       
  

#if SERVER
                                                               
 
	                             
	                                                           
	 
		                           
			                 
	 

	                                                                                        

	           
 
#endif         


#if SERVER
                                                     
 
	                                        
	 
		                     
			        
		                                      
		            
	 
 
#endif         



#if SERVER
                                                                                 
 
	                   

	                                       
	                                           

	                 
 
#endif         

#if SERVER
                                                               
 
	                             
	                                                              
	                                          

	                              
 

                                                          
 
	                             
	                                                     
	                            
 
#endif         



#if SERVER
                                                                                 
 
	                                                 
		            

	                                                    
		            

	                                                  
		            

	                         
	 
		                                                                                                
		            
	 

	                         
	 
		                                                                                              
		            
	 

	                              
	 
		                                                                                                    
		            
	 

	                                                
	                                                                     
	 
		                                                                                                           
		            
	 

	           
 
#endif         


#if SERVER && DEV
                                                              
 
	                   

	                                                                                                         

	                                                                               
	                                                                          
	                                 
		                                                                                                                                                                        

	                                                                                                                                    
	                                                                                                               
	                   
	                            
	                            

	                                                                                                                          
	                          

	                                              
	                                            
	                                           
	                                                    

	             
	 
		                                                                           
		                                                             
		      
		                                                                  
		                                                                                                                          

	 

 
#endif                


#if SERVER
                                                            
 
	                           
		      

	                                        
 
#endif         

#if SERVER
                                                                                                             
 
	                                                              

	       
		                                                    
		 
			                                                                                           
		 
	      

	                                                      
 
#endif         



#if SERVER
                                                                                                                       
 
	                                                              

	       
		                                                              
		 
			                                                                                           
		 
	      

	                                                                
 
#endif         



#if SERVER
                                                                                                              
 
	                                                              

	       
		                                                     
		 
			                                                                                           
		 
	      

	                                                       
 
#endif         



#if SERVER
                                                                                                                        
 
	                                                              

	       
		                                                               
		 
			                                                                                           
		 
	      

	                                                                 
 
#endif         



#if SERVER
                                                                                                                           
 
	                                                              

	       
		                                                          
		 
			                                                                                           
		 
	      

	                                                            
 
#endif         

#if SERVER
                                                        
 
	                                                 
	 
		                                         
			           
	 

	            
 
#endif
