                  

                                                         
                                                         

                                                                        

                                                                                                               
 
                                                                 
                                                                                                
                               

                                                       
  
                           
                               
                     

                                         
                                                                                                         
                                     
  
 

                                                                                                            
 
                                                                   

                                           

                                          
                                         
                                         
                                           
                                 
                                                     
                                                         
                                                 
                                        
                                            
                                                            

            
  
            
                                                                              
                               
       
                                               
                                         
        
  

           
                                    
                                                                                  
                                                                   
                                                       
       
 

                                                                                                                                                                       
 
                                    
                                                                                     
                                                                                    
                   
          
  
                        
  
            
                  
                  
                 
  

                                                                 

                       
          


           
                                               
   
                                                                                             
                                                                                               
                                                                            
                                                                
   
      
   
                                                                         
                                                                            
                                                                

   


                                   
                                    
       

           
                                                                                           
       
                                     
  
 
                           

global function OnWeaponPrimaryAttack_weapon_creaturebait
global function OnProjectileCollision_weapon_creaturebait

var function OnWeaponPrimaryAttack_weapon_creaturebait( entity weapon, WeaponPrimaryAttackParams attackParams )                                      
{
}
void function OnProjectileCollision_weapon_creaturebait( entity projectile, vector pos, vector normal, entity hitEnt, int hitbox, bool isCritical, bool isPassthrough )
{
	projectile.SetVelocity( <0, 0, 0> )
}
                                     
